accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('register', views.register, name='register')
]

blog/urls.py
from . import views
from django.urls import path
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('categories', views.categories, name='categories'),
    path('articles/<str:id>', views.singleArt, name='singleArt'),
    path('bookmarks', views.bookmarks, name= "bookmarks"),
    path('category/<str:name>', views.category, name = 'category'),
    path('update/<str:id>', views.update, name= "update"),
    # APIs
    path('save/<str:id>', views.save, name="save"),
    path('category/save/<str:id>', views.save, name="save"),
    path('vote/<str:id>', views.voting, name='vote'),
    path('category/vote/<str:id>', views.voting, name='vote'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('category/delete/<str:id>', views.delete, name='delete'),
    path('articles/comment/<str:id>', views.addComment, name='addComment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.error404'

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from datetime import datetime    
from django.utils.timezone import now
# Create your models here.

class Article(models.Model):
  categoryList = [
        ("javascript" , "JavaScript"),
        ("web develpment" , "Web Develpment"),
        ("react" , "React"),
        ("python" , "Python"),
        ("other", "Other"),
    ]
  owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles')
  title = models.CharField(max_length = 200)
  desc = models.CharField(max_length = 200)
  artImage = models.ImageField(upload_to = 'art_photos', default = './images/default.jpg', null = True, blank = True)
  content = models.TextField()
  category = MultiSelectField(choices=categoryList,  max_choices=3)
  created = models.DateTimeField(default=now, editable=False) 
  bookmarks = models.ManyToManyField(User, related_name='bookmarks')
  upvote = models.ManyToManyField(User, related_name='up')
  downvote = models.ManyToManyField(User, related_name='down')
  
  class Meta:
    ordering = ['-created']
  def  __str__(self):
    return f'{self.owner} writes an article at {self.created}'
  
class Comment(models.Model):
  owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')
  article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name = 'article')
  created = models.DateTimeField(default=now, editable=False)
  content = models.TextField(max_length = 200)
  class Meta:
    ordering = ['-created']
  def __str__(self):
    return f"{self.owner} write a comment at {self.created}"

blog/forms.py
from .models import Article
from django import forms

class CreateArt(forms.ModelForm):
  class Meta:
    model = Article
    fields = ['title', 'artImage', 'desc', 'content', 'category']
    
    # widgets = {
    #   'title': forms.TextInput(attrs = {'class': 'dark-form form-control'}),
    #   'category': forms.CheckboxSelectMultiple(attrs= {'class': 'form-check-input category-select'}),
    #   }

blog/views.py
import json
import datetime
import time
from webbrowser import get
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import CreateArt
from .models import Article, Comment
from django.contrib import messages
import markdown2
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from django.contrib.auth.models import User
from django.db.models import Q
# Create your views here.
def index(request):
  if 'q' in request.GET and request.GET['q'] != '':
    q = request.GET['q']
    mutliQ = Q(Q(title__icontains = q) | Q(desc__icontains = q))
    articles = Article.objects.filter(mutliQ)
    message = f"All You need About \"{q}\""
  else :
    articles = Article.objects.all()
    message = False
  return render(request, 'index.html', {
    'articles': articles,
    'search': message,
  })

@login_required
def add(request):
  if request.method == "POST":
    form = CreateArt(request.POST, request.FILES)
    if form.is_valid():
      data = form.cleaned_data
      article = Article(owner = request.user, title = data['title'], artImage = data['artImage'], content = data['content'], desc = data['desc'], category = data['category'])
      article.save()
      messages.success(request, 'Article added successfully ^_^')
      return HttpResponseRedirect(reverse('blog:index'))
    
    return render(request, 'add.html', {
      'error': 'Not valid Data!',
      'form': CreateArt(),
      'mode': 'Create',
      })
    
  return render(request, 'add.html', {
    'form': CreateArt(),
    'mode': 'Create',
  })

def categories(request):
  return render(request, 'categories.html')

# single post
def singleArt(request, id):
  art = Article.objects.get(pk= id)
  comments = Comment.objects.filter(article = art).all()
  return render(request, 'singleArt.html', {
    'post': art,
    'content': markdown2.markdown(art.content),
    'comments': comments,
  })
  
  
  
# handle 404
def error404(request, exception):
  return render(request, '404.html')

@login_required
@csrf_exempt
def save(request, id):
  if request.method == "POST":
    getArticle = Article.objects.get(pk = id)
    if request.user in getArticle.bookmarks.all():
      getArticle.bookmarks.remove(request.user)
      return JsonResponse({"message": "removed"})
    else:
      getArticle.bookmarks.add(request.user)
      return JsonResponse({"message": "added"})
    

@login_required
def bookmarks(request):
  return render(request, 'bookmarks.html', {
    'postsMarked': Article.objects.filter(bookmarks = request.user).all(),
  })
  

def category(request, name):
  targetArticles = []
  allArticles = Article.objects.all()
  for art in allArticles:
    for cat in art.category:
      if (cat == name):
        targetArticles.append(art)
  
  return render(request, 'category.html', {
    'title': name,
    'targetArticle': targetArticles,
  })
  
@login_required 
@csrf_exempt
def voting(request, id):
  targtArticle = Article.objects.get(pk = id)
  if request.user.is_authenticated:
    if request.method == "PUT":
      if request.user in targtArticle.upvote.all():
        targtArticle.upvote.remove(request.user)
        return JsonResponse({'messege': 'downvote', 'count': targtArticle.upvote.count()})
      else:
        targtArticle.upvote.add(request.user)
        return JsonResponse({'messege': 'upvote', 'count': targtArticle.upvote.count()})
  
  else:
    return HttpResponseRedirect(reverse('index'))
  
  
  
@login_required
@csrf_exempt
def delete(request, id):
  targtArticle = Article.objects.get(pk = id)
  if request.user.is_authenticated and targtArticle.owner == request.user:
    if request.method == "POST":
      targtArticle.delete()
    return JsonResponse({'message': 'deleted'})
  else:
    return HttpResponseRedirect(reverse('index'))
    
@login_required
def update(request, id):
  targetArticle = Article.objects.get(pk = id)
  form = CreateArt(instance=targetArticle)
  if request.method == "POST":
    form = CreateArt(request.POST, request.FILES, instance=targetArticle)
    if form.is_valid():
      form.save()
      messages.success(request, 'Article Updated successfully ^_^')
      return HttpResponseRedirect(reverse('blog:index'))
    else:
      return render(request, 'add.html', {
        'form': form,
        'mode': 'Update',
        })
  return render(request, 'add.html', {
    'form': form,
    'mode': 'Update',
  })
  
@login_required
@csrf_exempt
def addComment(request, id):
  if request.user.is_authenticated:
    if request.method == "POST":
      targetArticle = Article.objects.get(pk = id)
      data = json.loads(request.body)
      content = data.get('comment')
      if content == '':
        return HttpResponseRedirect(reverse('blog:singleArt', kwargs={'id':id}))
      newComment = Comment(owner = request.user, article = targetArticle, content = content)
      newComment.save()
      return JsonResponse({
        'content': newComment.content, 
        'owner': request.user.username, 
        'created': newComment.created, 
        'numbComments': Comment.objects.filter(article = targetArticle).count()
        })
  return HttpResponseRedirect(reverse('blog:singleArt', kwargs={'id':id}))

blog/templates/add.html
{% extends './layout.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block links %}
  <link rel="stylesheet" href="{% static 'css/add.css' %}">
{% endblock links %}

{% block title %}
  Write Blog 
{% endblock title %} 
{% block body %}


<div class="container form-group add-form">
  {% if error %}
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <strong>{{error}}</strong> You should check in on some of those fields below(image || category- at most three).
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endif %}
  <form
    action=""
    class="col-sm-10"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %} 
    <div class="title-art">
      {{ form.title|as_crispy_field }} 
    </div>
    <hr>
    <div class="desc-art">
      <small style="color: var(--bs-cyan);">Tip: Write Summary about this Article..</small>
      {{ form.desc|as_crispy_field }}
    </div>
    <hr>
    <div class="image-art">
      {{ form.artImage|as_crispy_field }}
    </div>
    <hr>
    <div class="content-art">
      <small style="color: var(--bs-cyan);">Tip: You can write with <a target="_blank" href="https://www.markdownguide.org/basic-syntax">Markdown</a> syntax</small>
      {{ form.content|as_crispy_field }}
    </div>
    <hr>
    <div class="categorya-art">
      <small style="color: var(--bs-cyan);">Tip: Choose at most three..</small>
      {{form.category|as_crispy_field }}
    </div>
    <input type="submit" value="{{ mode }}" class="btn btn-info" />
  </form>
  
</div>
{% endblock body %}

blog/templates/bookmarks.html
{% extends './layout.html' %} 
{% load static %} 
{% block title %} 
BookMarks 
{%endblock title %} 

{% block links %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock links %} 

{% block body %}
<div class="container blog-content">
  {% for post in postsMarked %}
  <article class="postcard dark blue" data-card="{{post.id}}">
    <a class="postcard__img_link" href="{% url 'blog:singleArt' post.id %}">
      
      {% if post.artImage %} 
        <img
          class="postcard__img"
          src="{{ post.artImage.url }}"
          alt="Image Title"
        />
      {% else %}
        <img
        class="postcard__img"
        src="../../media/images/default.jpg"
        alt="Image Title"
        />
      {% endif %}
        
    </a>
    <div class="postcard__text">
      <h1 class="postcard__title blue"><a href="{% url 'blog:singleArt' post.id %}">{{ post.title }}</a></h1>
      <div class="postcard__subtitle small">
          <i class="fas fa-calendar-alt mr-2"></i>{{ post.created }}
      </div>
      <div class="postcard__bar"></div>
      <div class="postcard__preview-txt">
        {{ post.desc }}
      </div>
      <ul class="postcard__tagbox">
        
        {% for cat in post.category %}
        <li class="tag__item"><i class="fas fa-tag mr-2"></i>{{cat}}</li>
        {% endfor %}
        <!-- <li class="tag__item"><i class="fas fa-clock mr-2"></i>5 mins.</li> -->
        {% if user.is_authenticated %}
          {% if user in post.bookmarks.all %}
          <li class="tag__item play blue save saved" id="{{ post.pk}}">
            <i class="fa-regular fa-bookmark"></i><span class="save-txt">Saved</span>
          </li>
          {% else %}  
          <li class="tag__item play save blue pointed" id="{{post.id}}"data-bs-toggle="tooltip" data-bs-title="Default tooltip">
            <i class="fa-regular fa-bookmark"></i><span class="save-txt">Save</span>
          </li>
          {% endif %}
          {% if user != post.owner %}
            {% if user in post.upvote.all %}
              <li class="tag__item play blue vote voted" data-vote="{{ post.id }}">
                <i class="fa-solid fa-angle-up"></i><span class="vote-num">{{ post.upvote.count }}</span>
              </li>
            {% else %}
              <li class="tag__item play blue vote" data-vote="{{ post.id }}">
                <i class="fa-solid fa-angle-up"></i><span class="vote-num">{{ post.upvote.count }}</span>
              </li>
            {% endif %}
          {% else %}
            <li class="tag__item play blue">
              <span>{{ post.upvote.count }} vote</span>
            </li>
          {% endif %}
          
          {% if user == post.owner %}
          <li class="tag__item play blue delete pointed" data-delete="{{post.id}}">
            <i class="fa-regular fa-trash-can"></i>
          </li>
          <a href="{% url 'blog:update' post.id %}">
            <li class="tag__item play blue pointed" data-update="{{post.id}}">
              <i class="fa-regular fa-pen-to-square"></i> Update
            </li>
          </a>
          {% endif %}
            
        {% endif %}
      </ul>
    </div>
  </article>
  {% empty %}
  <div class="alert alert-info" role="alert">
    <strong>There are no Aritcles Saved right now.</strong>
  </div>
  {% endfor %}
</div>
{% endblock body %}

blog/templates/categories.html
{% extends './layout.html' %} 
{% load static %} 
{% block title %} 
Categories 
{%endblock title %} 

{% block links %}
<link rel="stylesheet" href="{% static 'css/category.css' %}" />
{% endblock links %} 



{% block body %}
<div class="header">
  <h1>Categories😎</h1>
  <hr>
</div>
<div class="categorys">
  <a href="{% url 'blog:category' 'javascript' %}"
    ><div class="profile-card-2">
      <img
        src="../../media/images/javascript.jpg"
        class="img img-responsive"
      />
      <div class="profile-name">JavaScript</div>
    </div></a
  >
  <a href="{% url 'blog:category' 'python' %}"
    ><div class="profile-card-2">
      <img
        src="../../media/images/python.jpg"
        class="img img-responsive"
      />
      <div class="profile-name">Python</div>
    </div></a
  >
  <a href="{% url 'blog:category' 'react' %}"
    ><div class="profile-card-2">
      <img
        src="../../media/images/react.jpg"
        class="img img-responsive"
      />
      <div class="profile-name">React</div>
    </div></a
  >
  <a href="{% url 'blog:category' 'web develpment' %}"
    ><div class="profile-card-2">
      <img
        src="../../media/images/web.jpg"
        class="img img-responsive"
      />
      <div class="profile-name">Web Devolpment</div>
    </div></a
  >
  <a href="{% url 'blog:category' 'other' %}"
    ><div class="profile-card-2">
      <img
        src="../../media/images/other.jpg"
        class="img img-responsive"
      />
      <div class="profile-name">Other..</div>
    </div></a
  >
</div>
{% endblock body %}

blog/templates/category.html
{% extends './layout.html' %}
{% load static %}


{% block title %}
  {{ title }}
{% endblock title %}
  

{% block links %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock links %}
  

{% block body %}
<div class="header">
  <h1>All Articles in {{title}}🤩</h1>
  <hr>
</div>
<div class="container blog-content">
  {% for post in targetArticle %}
  <article class="postcard dark blue" data-card="{{post.id}}">
    <a class="postcard__img_link" href="{% url 'blog:singleArt' post.id %}">
      
      {% if post.artImage %} 
        <img
          class="postcard__img"
          src="{{ post.artImage.url }}"
          alt="Image Title"
        />
      {% else %}
        <img
        class="postcard__img"
        src="../../media/images/default.jpg"
        alt="Image Title"
        />
      {% endif %}
        
    </a>
    <div class="postcard__text">
      <h1 class="postcard__title blue"><a href="{% url 'blog:singleArt' post.id %}">{{ post.title }}</a></h1>
      <div class="postcard__subtitle small">
          <i class="fas fa-calendar-alt mr-2"></i>{{ post.created }}
      </div>
      <div class="postcard__bar"></div>
      <div class="postcard__preview-txt">
        {{ post.desc }}
      </div>
      <ul class="postcard__tagbox">
        
        {% for cat in post.category %}
        <li class="tag__item"><i class="fas fa-tag mr-2"></i>{{cat}}</li>
        {% endfor %}
        <!-- <li class="tag__item"><i class="fas fa-clock mr-2"></i>5 mins.</li> -->
        {% if user.is_authenticated %}
          {% if user in post.bookmarks.all %}
          <li class="tag__item play blue save saved" id="{{ post.pk}}">
            <i class="fa-regular fa-bookmark"></i><span class="save-txt">Saved</span>
          </li>
          {% else %}  
          <li class="tag__item play save blue pointed" id="{{post.id}}"data-bs-toggle="tooltip" data-bs-title="Default tooltip">
            <i class="fa-regular fa-bookmark"></i><span class="save-txt">Save</span>
          </li>
          {% endif %}
          {% if user != post.owner %}
            {% if user in post.upvote.all %}
              <li class="tag__item play blue vote voted" data-vote="{{ post.id }}">
                <i class="fa-solid fa-angle-up"></i><span class="vote-num">{{ post.upvote.count }}</span>
              </li>
            {% else %}
              <li class="tag__item play blue vote" data-vote="{{ post.id }}">
                <i class="fa-solid fa-angle-up"></i><span class="vote-num">{{ post.upvote.count }}</span>
              </li>
            {% endif %}
          {% else %}
            <li class="tag__item play blue">
              <span>{{ post.upvote.count }} vote</span>
            </li>
          {% endif %}
          
          {% if user == post.owner %}
          <li class="tag__item play blue delete pointed" data-delete="{{post.id}}">
            <i class="fa-regular fa-trash-can"></i>
          </li>
          <a href="{% url 'blog:update' post.id %}">
            <li class="tag__item play blue pointed" data-update="{{post.id}}">
              <i class="fa-regular fa-pen-to-square"></i> Update
            </li>
          </a>
          {% endif %}
            
        {% endif %}
      </ul>
    </div>
  </article>
  {% empty %}
  <div class="alert alert-info" role="alert">
    <strong>There are no Aritcles on this category.</strong>
  </div>
  {% endfor %}
</div>
{% endblock body %}
  

blog/templates/index.html
{% extends './layout.html' %} 
{% load static %} 
{% block links %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock links %}
{% block body %}
<div class="header">
  {% if search %}
    <h1>{{search}}</h1>
    {% else %}
    <h1>All you need in Tech.👌</h1>
  {% endif %}
  <hr>
</div>
<div class="messege container">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ message }}✔</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
</div>
<div class="container blog-content">
  {% for post in articles %}
  <article class="postcard dark blue" data-card="{{post.id}}">
    <a class="postcard__img_link" href="{% url 'blog:singleArt' post.id %}">
      
      {% if post.artImage %} 
        <img
          class="postcard__img"
          src="{{ post.artImage.url }}"
          alt="Image Title"
        />
      {% else %}
        <img
        class="postcard__img"
        src="../../media/images/default.jpg"
        alt="Image Title"
        />
      {% endif %}
        
    </a>
    <div class="postcard__text">
      <h1 class="postcard__title blue"><a href="{% url 'blog:singleArt' post.id %}">{{ post.title }}</a></h1>
      <div class="postcard__subtitle small">
          <i class="fas fa-calendar-alt mr-2"></i>{{ post.created }}
      </div>
      <div class="postcard__bar"></div>
      <div class="postcard__preview-txt">
        {{ post.desc }}
      </div>
      <ul class="postcard__tagbox">
        
        {% for cat in post.category %}
        <li class="tag__item"><i class="fas fa-tag mr-2"></i>{{cat}}</li>
        {% endfor %}
        <!-- <li class="tag__item"><i class="fas fa-clock mr-2"></i>5 mins.</li> -->
        {% if user.is_authenticated %}
          {% if user in post.bookmarks.all %}
          <li class="tag__item play blue save saved" id="{{ post.pk}}">
            <i class="fa-regular fa-bookmark"></i><span class="save-txt">Saved</span>
          </li>
          {% else %}  
          <li class="tag__item play save blue pointed" id="{{post.id}}"data-bs-toggle="tooltip" data-bs-title="Default tooltip">
            <i class="fa-regular fa-bookmark"></i><span class="save-txt">Save</span>
          </li>
          {% endif %}
          {% if user != post.owner %}
            {% if user in post.upvote.all %}
              <li class="tag__item play blue vote voted" data-vote="{{ post.id }}">
                <i class="fa-solid fa-angle-up"></i><span class="vote-num">{{ post.upvote.count }}</span>
              </li>
            {% else %}
              <li class="tag__item play blue vote" data-vote="{{ post.id }}">
                <i class="fa-solid fa-angle-up"></i><span class="vote-num">{{ post.upvote.count }}</span>
              </li>
            {% endif %}
          {% else %}
            <li class="tag__item play blue">
              <span>{{ post.upvote.count }} vote</span>
            </li>
          {% endif %}
          
          {% if user == post.owner %}
          <li class="tag__item play blue delete pointed" data-delete="{{post.id}}">
            <i class="fa-regular fa-trash-can"></i>
          </li>
          <a href="{% url 'blog:update' post.id %}">
            <li class="tag__item play blue pointed" data-update="{{post.id}}">
              <i class="fa-regular fa-pen-to-square"></i> Update
            </li>
          </a>
          {% endif %}
            
        {% endif %}
      </ul>
    </div>
  </article>
  {% empty %}
  
  {% if search %}
    <div class="alert alert-info" role="alert">
      <strong>OOPS, There are no articles with this title 😥...</strong> 
    </div>
  {% else %}  
    <div class="alert alert-info" role="alert">
      <strong>There are no Aritcles right now.</strong> 
    </div>
  {% endif %}
    
  {% endfor %}
</div>

{% endblock body %}

blog/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
      integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}" />
    <script
      src="https://kit.fontawesome.com/4e362c2153.js"
      crossorigin="anonymous"
    ></script>
    {% block links %} {% endblock links %}

    <title>{% block title %} Blog {% endblock title %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'semicolon.png' %}"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="padding: 15px">
      <div class="container-fluid">
        <a
          class="navbar-brand"
          href="{% url 'blog:index' %}"
          style="color: var(--bs-cyan); font-family: monospace; font-size:28px;"
          >Semicolon;</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto ulNav">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'blog:index' %}"
                ><i class="fa-solid fa-house"></i>My Feed</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'blog:categories' %}"
                ><i class="fa-solid fa-layer-group"></i>Categories</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'blog:add' %}"
                ><i class="fa-regular fa-pen-to-square"></i>Add Article</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'blog:bookmarks' %}"
                ><i class="fa-solid fa-book-bookmark"></i>Bookmarks</a
              >
            </li>
            <li class="nav-item dropdown active">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <i class="fa-regular fa-circle-user"></i> {{user}}
              </a>
              <ul class="dropdown-menu">
                <!-- <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li> -->
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="{% url 'logout' %}"
                    ><i class="fa-solid fa-arrow-right-from-bracket"></i
                    >Logout</a
                  >
                </li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'accounts:register' %}"
                >Register</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex" role="search" method="get" action="{% url 'blog:index' %}">
            <input
              class="form-control me-2 input-search"
              type="search"
              placeholder="Search"
              aria-label="Search"
              name="q"
            />
            <button class="btn btn-outline-info search" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <div class="blog-content1">
      {% block body %} 
      {% endblock body %}
      <div id="snackbar"></div>
    </div>
    <div class="footer">
      <footer
        class="text-center text-lg-start text-white"
        style="background-color: #1c2331"
      >
        <section class="footer-social">
          <a href="mailto:bederahmed0@gmail.com">
            <i class="fa-regular fa-envelope"></i>
          </a>
          <a href="https://www.linkedin.com/in/ahmed-bedeir-45b0171bb/">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="https://github.com/AhmedBedeir">
            <i class="fab fa-github"></i>
          </a>
        </section>
        <!-- Copyright -->
        <div
          class="text-center p-3"
          style="background-color: rgba(0, 0, 0, 0.2)"
        >
          © <span class="thisYear"></span>
          <a
            class=""
            target="_blank"
            href="https://www.linkedin.com/in/ahmed-bedeir-45b0171bb/"
            >Bedeir.</a
          >
          All Rights Reserved.
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
    </div>
    <!-- End of .container -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>
      const date = new Date();
      const year = document.querySelector('.thisYear');
      year.innerHTML = date.getFullYear();
    </script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      });
    </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </body>
</html>